### ISSUE TITLE
phantomjs sometimes stops receiving connections

### ISSUE THREAD

**Issue by pofider** [pofider/phantom-workers#13]
We encountered situation in which phantomjs worker stopped receiving connection and ECONNREFUSED errors where thrown. This took couple of minutes until phantomjs completely failed or was recycled by the manager because of the timeout.

The solution for such processing freeze should be to auto recycle phantomjs when ECONNREFUSED is thrown.

**Comment by pofider** [comment]
@bjrmatos Please shortly review the above commit.

**Comment by bjrmatos** [comment]
LGTM 👌

**Comment by pofider** [comment]
Great. Closing. Will be part of the next release.
