### ISSUE TITLE
iisnode/windows azure support

### ISSUE THREAD

**Issue by bjrmatos** [pofider/phantom-workers#6]
Hi, in the past days i was trying to make jsreport work on iisnode, i was using the "phantom-server" strategy but i got caught by [this error](https://groups.google.com/forum/#!topic/jsreport/Jp_c9ZILd5s), after some re-search i found that [issnode don't have notion of stdin](https://github.com/tjanczuk/iisnode/issues/337).. i saw [another project handle this issue not using stdin when running on issnode](https://github.com/evantahler/actionhero/commit/465a85fba9800466ab9ca3d5df65a18f7decd830).

After seeing the code in https://github.com/pofider/phantom-workers/blob/master/lib/phantomWorker.js#L68 i wonder why just don't pass the PORT as an env variable via [`child_process.execFile` options](https://nodejs.org/docs/v0.10.40/api/child_process.html#child_process_child_process_execfile_file_args_options_callback) and get it in the phantom script in this way:

``` js
var system = require('system');
var PHANTOM_WORKER_PORT = system.env['PHANTOM_WORKER_PORT'];
```

with these changes phantom-workers can be used in iisnode/azure with all the performance gains that it have

if you are ok with this i could send you a PR .. let me know :)

**Comment by pofider** [comment]
Hi, perfect. 

The script part change must be done in both
https://github.com/pofider/html-to-xlsx
https://github.com/pofider/phantom-html-to-pdf

I can easily fix it, or if you want to send me a pull request, I am ready to accept.

**Comment by bjrmatos** [comment]
i can easily send you PRs for html-to-xlsx and phantom-html-to-pdf but first we need a new release for phantom-workers in order to update dependencies

**Comment by bjrmatos** [comment]
so, the only thing left to do is publish to npm and make the changes to:

https://github.com/pofider/html-to-xlsx
https://github.com/pofider/phantom-html-to-pdf

i will send PR's to both projects when the next version is published

**Comment by bjrmatos** [comment]
done!
