### ISSUE TITLE
PhantomJS 2.0 support

### ISSUE THREAD

**Issue by surjikal** [pofider/phantom-workers#9]
Hey guys, it would be nice if this library supported PhantomJS 2.0.

I know that the phantomjs node package does not support it yet, but there is another way.. This particular phantomjs cluster module (https://github.com/buzzvil/ghost-town) allows me to set the PhantomJS binary, which means I can make it use version 2.0. Maybe you could apply this method to your module?

The reason I need PhantomJS 2.0 support is mainly for flexbox support.

**Comment by pofider** [comment]
Hi, yes, it is in our short-term plan. Thanks for the link and suggestion.

**Comment by pofider** [comment]
This is supported through `phantomPath` option

See [readme](https://github.com/pofider/phantom-workers#phantomjs2)
